language: python

sudo: false

python:
  - 3.5.2
  # - nightly

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then pip install uvloop; fi

script:
  - python setup.py test --coverage -q
  - flake8
  - python setup.py test --coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then python setup.py test -q --io uv; fi

notifications:
  email: false
