language: python

sudo: false

python:
  - 3.5.1

services:
  - redis-server

install:
  - pip install git+https://github.com/quantmind/pulsar.git@dev

script:
  - python setup.py test --coverage
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5.1' ]]; then python setup.py --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - dev
